---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app2
  name: deployment-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-app2
  template:
    metadata:
      labels:
        app: app-app2
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-cache-enable: "true"
        vault.hashicorp.com/ca-cert: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        vault.hashicorp.com/role: 'app2'
        vault.hashicorp.com/agent-inject-secret-config.env: 'secret/data/services/app2/config'
        vault.hashicorp.com/agent-inject-template-config.env: |
          {{- with secret "secret/data/services/app2/config" -}}
          {{- range $key, $value := .Data.data }}
            export {{ $key }}={{ $value }}
            {{- end }}
          {{- end -}}
    spec:
      serviceAccountName: sa-app2
      containers:
      - name: app-app2
        image: nginx:latest
        command: ["/bin/bash", "-c"]
        args: [ "for f in /vault/secrets/*.env; do source $f; done && nginx -g 'daemon off;'" ]
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
