---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp2
  name: deployment-myapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-myapp2
  template:
    metadata:
      labels:
        app: app-myapp2
    spec:
      containers:
      - name: app-myapp2
        image: nginx:latest
        ports:
        - name: web
          containerPort: 8000
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
