---
apiVersion: v1
kind: Service
metadata:
  namespace: myapp2
  name: service-myapp2
spec:
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: app-myapp2
