---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubecron1
  namespace: kubecron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-cache-enable: "true"
            vault.hashicorp.com/ca-cert: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            vault.hashicorp.com/role: 'kubecron1'
            vault.hashicorp.com/agent-inject-secret-config.env: 'secret/data/services/kubecron1/config'
            vault.hashicorp.com/agent-inject-template-config.env: |
              {{- with secret "secret/data/services/kubecron1/config" -}}
              {{- range $key, $value := .Data.data }}
                export {{ $key }}={{ $value }}
                {{- end }}
              {{- end -}}
        spec:
          serviceAccountName: sa-kubecron1
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args: [ "for f in /vault/secrets/*.env; do source $f; done && echo secret from vault, injected into env variables: ${url}, ${token}" ]
          restartPolicy: OnFailure
