---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: default
  source:
    chart: grafana
    helm:
      values: |
        adminUser: jroot

        persistence:
          type: pvc
          enabled: false
          storageClassName: gp2-encrypted

        ingress:
          enabled: true
          ingressClassName: alb
          annotations:
            external-dns.alpha.kubernetes.io/hostname: grafana.blendsecuritylab.com
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
              { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          hosts:
            - grafana.blendsecuritylab.com
          extraPaths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: ssl-redirect
                  port:
                    name: use-annotation
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: grafana
                  port:
                    number: 80

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                isDefault: true
              - name: Loki
                type: loki
                url: http://loki-loki-distributed-gateway

        envFromSecrets:
          - name: gf-auth-okta-client-secret
            optional: false

        grafana.ini:
          server:
            root_url: https://grafana.blendsecuritylab.com
          auth.okta:
            name: Okta
            icon: okta
            enabled: true
            allow_sign_up: true
            client_id: 0oa531kjo83vT7SEm1d7
            client_secret: notthesecret
            scopes: openid profile email groups
            auth_url: https://blendsandbox.oktapreview.com/oauth2/default/v1/authorize
            token_url: https://blendsandbox.oktapreview.com/oauth2/default/v1/token
            api_url: https://blendsandbox.oktapreview.com/oauth2/default/v1/userinfo
            allowed_domains: blend.com
            role_attribute_path: contains(groups[*], 'team-blend-infosec-operations') && 'Admin'
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.35.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
