---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: default
  source:
    chart: grafana
    helm:
      values: |
        adminUser: jroot
        persistence:
          type: pvc
          enabled: false
          storageClassName: gp2-encrypted
        ingress:
          enabled: true
          ingressClassName: alb
          annotations:
            external-dns.alpha.kubernetes.io/hostname: grafana.blendsecuritylab.com
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
              { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          hosts:
            - grafana.blendsecuritylab.com
          extraPaths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: ssl-redirect
                  port:
                    name: use-annotation
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: grafana
                  port:
                    number: 80

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                isDefault: true
              - name: Loki
                type: loki
                url: http://loki-loki-distributed-gateway
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.35.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
