---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: default
  source:
    chart: vector
    repoURL: https://helm.vector.dev
    helm:
      values: |
        role: Agent
        tolerations:
          - key: "taint_for_vault"
            operator: "Equal"
            value: "true"
            effect: "NoExecute"

        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"

        customConfig:
          data_dir: "/vector-data-dir"
          api:
            enabled: true
            address: 127.0.0.1:8686
            playground: false
          sources:
            k8s_all:
              type: "kubernetes_logs"
          sinks:
            loki:
              type: "loki"
              inputs:
                - k8s_all
              endpoint: "http://loki-loki-distributed-gateway"
              encoding:
                codec: "json"
              compression: "none"
              labels:
                stream: "{{` {{ stream }} `}}"
                source_type: "{{` {{ source_type }} `}}"
                k8s_pod_namespace: "{{` {{ kubernetes.pod_namespace }} `}}"
    targetRevision: 0.16.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
