---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app2
    name: in-cluster
  project: default
  source:
    path: deployment/app2/overlays/dev
    repoURL: https://github.com/hermes2000/argocdtest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
