---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecron1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubecron
    name: in-cluster
  project: default
  source:
    path: deployment/kubecron1/overlays/dev
    repoURL: https://github.com/hermes2000/argocdtest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
