---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageclass
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment/storageclass
    repoURL: https://github.com/hermes2000/argocdtest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
