---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app1
  name: deployment-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-app1
  template:
    metadata:
      labels:
        app: app-app1
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/ca-cert: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        vault.hashicorp.com/role: 'app1'
        vault.hashicorp.com/agent-inject-secret-api-token.json: 'secret/data/services/app1/api_token'
    spec:
      serviceAccountName: sa-app1
      containers:
      - name: app-app1
        image: nginx:latest
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
